### ISSUE TITLE
New child devices on container restart

### ISSUE THREAD

**Issue by mstoffel-sag** [thin-edge/tedge-demo-container#30]
When I  stop the tedge-demo-container docker solution (docker compose stop) and start it afterwards again I end up with multiple child devices.

![image](https://github.com/thin-edge/tedge-demo-container/assets/29426188/adc1e473-3161-47ed-8583-208b0fafe205)

Is there a way to prevent this from happening?

Thanks,

Marco

**Comment by reubenmiller** [comment]
The child devices are being created because in some instances measurements (such as cpu and memory) are sent as measurement before the service has been fully registered in the cloud. If Cumulocity received measurements via MQTT and no devices can be found, then it creates a child device automatically.

I'll look at disabling the container metrics to avoid this problem until the service registration offers a mechanism to prevent this.

**Comment by reubenmiller** [comment]
@mstoffel-sag the `tedge-container-plugin` has been updated to a version where the root cause has been fixed.

Try again with the latest version of the demo, [20230516.1](https://github.com/thin-edge/tedge-demo-container/releases/tag/20230516.1).

Note: If you are using the same managed object in Cumulocity, then you might need to manually unlink the services which have been linked as a child device instead of a service. Otherwise just create a new main device id and everything should just work.

**Comment by mstoffel-sag** [comment]
tested that. Works much better now. Thanks!
